import { createReadStream, existsSync, mkdirSync } from "node:fs";
import { readdir, rename, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { chromium } from "playwright-core";

const ROOT = path.resolve(import.meta.dirname, "..");
const DEFAULT_LINKS = path.join(ROOT, "data", "raw", "spotify", "official", "download_links.csv");
const DEFAULT_OUT_DIR = path.join(ROOT, "data", "raw", "spotify", "official");
const DEFAULT_PROFILE_DIR = path.join(ROOT, ".spotify-charts-profile");
const DEBUG_DIR = path.join(ROOT, "data", "raw", "spotify", "official", "_debug");

function parseArgs() {
  const args = process.argv.slice(2);
  const options = {
    links: DEFAULT_LINKS,
    outDir: DEFAULT_OUT_DIR,
    profileDir: DEFAULT_PROFILE_DIR,
    limit: Number.POSITIVE_INFINITY,
    startAt: 0,
    headed: true,
    skipExisting: true,
    loginFirst: false,
    sniff: false,
    apiFast: false,
    retries: 3,
    sleepMs: 250,
    rateLimitSleepMs: 60000,
  };

  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg === "--links") options.links = path.resolve(args[++i]);
    else if (arg === "--out-dir") options.outDir = path.resolve(args[++i]);
    else if (arg === "--profile-dir") options.profileDir = path.resolve(args[++i]);
    else if (arg === "--limit") options.limit = Number(args[++i]);
    else if (arg === "--start-at") options.startAt = Number(args[++i]);
    else if (arg === "--no-skip-existing") options.skipExisting = false;
    else if (arg === "--headless") options.headed = false;
    else if (arg === "--login-first") options.loginFirst = true;
    else if (arg === "--sniff") options.sniff = true;
    else if (arg === "--api-fast") options.apiFast = true;
    else if (arg === "--retries") options.retries = Number(args[++i]);
    else if (arg === "--sleep-ms") options.sleepMs = Number(args[++i]);
    else if (arg === "--rate-limit-sleep-ms") options.rateLimitSleepMs = Number(args[++i]);
    else if (arg === "--refresh-every") i += 1;
    else if (arg === "--help") {
      console.log(`Usage:
node scripts/download_spotify_official.mjs --limit 10

Options:
  --links <path>        CSV generated by make_spotify_official_links.py
  --out-dir <path>      Where downloaded CSV files should be stored
  --profile-dir <path>  Persistent browser profile for Spotify login
  --limit <n>           Max rows to process
  --start-at <n>        Zero-based row offset
  --no-skip-existing    Re-download files even if save_as already exists
  --login-first         Open Spotify Charts and wait for Enter before downloading
  --sniff               Print likely CSV/download network requests for the first processed row
  --api-fast            Capture the logged-in chart API headers once, then download JSON directly and save CSV
  --retries <n>         Retry failed API downloads this many times, default 3
  --sleep-ms <n>        Delay between API downloads in milliseconds, default 250
  --rate-limit-sleep-ms <n>  Delay after Spotify API 429 responses, default 60000
  --refresh-every <n>   Deprecated; ignored. Re-run the command manually for a fresh login capture.
  --headless            Run browser headless after login is already saved
`);
      process.exit(0);
    }
  }

  return options;
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function chartApiUrl(row) {
  const alias = `regional-${row.region}-${row.chart}`;
  return `https://charts-spotify-com-service.spotify.com/auth/v0/charts/${alias}/${row.date}`;
}

function csvCell(value) {
  const text = value == null ? "" : String(value);
  if (!/[",\n\r]/.test(text)) return text;
  return `"${text.replaceAll('"', '""')}"`;
}

function getNestedValue(object, paths) {
  for (const pathParts of paths) {
    let current = object;
    for (const part of pathParts) {
      current = current?.[part];
    }
    if (current != null && current !== "") return current;
  }
  return "";
}

function findChartEntries(payload) {
  if (Array.isArray(payload?.chartEntryViewResponses)) return payload.chartEntryViewResponses;

  const queue = [payload];
  let best = [];
  while (queue.length > 0) {
    const item = queue.shift();
    if (!item || typeof item !== "object") continue;

    if (Array.isArray(item)) {
      const looksLikeEntries = item.some(
        (entry) =>
          entry &&
          typeof entry === "object" &&
          ("chartEntryData" in entry || "trackMetadata" in entry || "currentRank" in entry),
      );
      if (looksLikeEntries && item.length > best.length) best = item;
      for (const child of item) queue.push(child);
      continue;
    }

    for (const value of Object.values(item)) queue.push(value);
  }

  return best;
}

function normalizeSpotifyImageUri(value) {
  if (!value) return "";
  const text = String(value);
  if (text.startsWith("http")) return text;
  if (text.startsWith("spotify:image:")) {
    return `https://i.scdn.co/image/${text.replace("spotify:image:", "")}`;
  }
  return text;
}

function entryToCsvRow(entry, row) {
  const data = entry.chartEntryData ?? entry.chartEntry ?? entry;
  const meta = entry.trackMetadata ?? entry.track ?? entry.metadata ?? {};
  const artistsRaw = meta.artists ?? meta.artistNames ?? meta.artist_names ?? data.artists ?? [];
  const artistNames = Array.isArray(artistsRaw)
    ? artistsRaw.map((artist) => artist.name ?? artist.artistName ?? artist).filter(Boolean).join(", ")
    : String(artistsRaw || meta.artistName || meta.artist_name || "");

  const rankingMetric = data.rankingMetric ?? data.ranking_metric ?? {};
  const rank = getNestedValue(
    { data, entry },
    [
      ["data", "currentRank"],
      ["data", "rank"],
      ["entry", "rank"],
    ],
  );
  const streams = getNestedValue(
    { data, rankingMetric, entry },
    [
      ["rankingMetric", "value"],
      ["data", "streams"],
      ["entry", "streams"],
    ],
  );

  return {
    rank,
    uri: meta.trackUri ?? meta.uri ?? meta.track_uri ?? "",
    artist_names: artistNames,
    track_name: meta.trackName ?? meta.name ?? meta.track_name ?? "",
    source: data.entryStatus ?? data.status ?? "",
    peak_rank: data.peakRank ?? data.peak_position ?? "",
    previous_rank: data.previousRank ?? data.previous_rank ?? "",
    weeks_on_chart: data.appearancesOnChart ?? data.weeksOnChart ?? data.weeks_on_chart ?? "",
    streams,
    chart_date: row.date,
    region: row.region,
    display_image_url: normalizeSpotifyImageUri(meta.displayImageUri ?? meta.display_image_uri ?? meta.imageUrl),
  };
}

function spotifyJsonToCsv(payload, row) {
  const entries = findChartEntries(payload);
  const headers = [
    "rank",
    "uri",
    "artist_names",
    "track_name",
    "source",
    "peak_rank",
    "previous_rank",
    "weeks_on_chart",
    "streams",
    "chart_date",
    "region",
    "display_image_url",
  ];
  const rows = entries.map((entry) => entryToCsvRow(entry, row)).filter((entry) => entry.rank && entry.track_name);
  const lines = [headers.join(",")];
  for (const item of rows) {
    lines.push(headers.map((header) => csvCell(item[header])).join(","));
  }
  return { csv: `${lines.join("\n")}\n`, count: rows.length };
}

function sanitizeApiHeaders(headers) {
  const allowed = [
    "authorization",
    "accept",
    "content-type",
    "app-platform",
    "spotify-app-version",
    "user-agent",
    "referer",
  ];
  const output = {};
  for (const key of allowed) {
    if (headers[key]) output[key] = headers[key];
  }
  output.accept = output.accept || "application/json";
  output["content-type"] = output["content-type"] || "application/json";
  output.referer = output.referer || "https://charts.spotify.com/";
  output["app-platform"] = output["app-platform"] || "Browser";
  return output;
}

async function captureApiHeaders(page, firstRow) {
  let capturedHeaders = null;
  const waiter = page
    .waitForRequest(
      (request) =>
        request.url().startsWith("https://charts-spotify-com-service.spotify.com/auth/v0/charts/") &&
        request.headers().authorization,
      { timeout: 45000 },
    )
    .then((request) => {
      capturedHeaders = sanitizeApiHeaders(request.headers());
      return capturedHeaders;
    })
    .catch((error) => {
      console.log(`[auth] could not capture API request: ${error.message}`);
      return null;
    });

  console.log(`[auth] opening ${firstRow.url}`);
  await page.goto(firstRow.url, { waitUntil: "domcontentloaded", timeout: 45000 }).catch((error) => {
    throw new Error(`Could not open Spotify Charts page for auth capture: ${error.message}`);
  });
  await waitForManualLogin(page);
  await page.waitForLoadState("networkidle", { timeout: 20000 }).catch(() => {});
  await waiter.catch(() => null);

  if (!capturedHeaders?.authorization) {
    throw new Error("Could not capture Spotify Charts API authorization header. Try --login-first in headed mode.");
  }

  return capturedHeaders;
}

async function getUsablePage(context) {
  const existing = context.pages().find((candidate) => !candidate.isClosed());
  return existing ?? context.newPage();
}

async function downloadViaApi(context, row, headers, outDir, retries, rateLimitSleepMs) {
  let lastError;
  for (let attempt = 0; attempt <= retries; attempt += 1) {
    try {
      const response = await context.request.get(chartApiUrl(row), { headers, timeout: 45000 });
      if (!response.ok()) {
        const retryAfter = Number(response.headers()["retry-after"] || 0);
        const message = `API returned ${response.status()} for ${row.save_as}`;
        if (attempt < retries && [408, 425, 429, 500, 502, 503, 504].includes(response.status())) {
          const backoffMs =
            response.status() === 429
              ? Math.max(retryAfter * 1000, rateLimitSleepMs)
              : Math.max(retryAfter * 1000, 1000 * (attempt + 1));
          console.log(`[retry ${attempt + 1}/${retries}] ${message}; waiting ${Math.round(backoffMs / 1000)}s`);
          await sleep(backoffMs);
          continue;
        }
        throw new Error(message);
      }

      const payload = await response.json();
      const { csv, count } = spotifyJsonToCsv(payload, row);
      if (count === 0) {
        throw new Error(`API response had no chart rows for ${row.save_as}`);
      }

      await writeFile(path.join(outDir, row.save_as), csv, "utf-8");
      return count;
    } catch (error) {
      lastError = error;
      if (attempt < retries) await sleep(1000 * (attempt + 1));
    }
  }

  throw lastError;
}

function parseCsvLine(line) {
  const cells = [];
  let current = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i += 1) {
    const char = line[i];
    if (char === '"' && line[i + 1] === '"') {
      current += '"';
      i += 1;
    } else if (char === '"') {
      inQuotes = !inQuotes;
    } else if (char === "," && !inQuotes) {
      cells.push(current);
      current = "";
    } else {
      current += char;
    }
  }
  cells.push(current);
  return cells;
}

async function readManifest(filePath) {
  if (!existsSync(filePath)) {
    throw new Error(`Missing links CSV: ${filePath}. Run scripts/make_spotify_official_links.py first.`);
  }

  const text = await new Promise((resolve, reject) => {
    let data = "";
    const stream = createReadStream(filePath, { encoding: "utf-8" });
    stream.on("data", (chunk) => {
      data += chunk;
    });
    stream.on("end", () => resolve(data));
    stream.on("error", reject);
  });

  const lines = text.split(/\r?\n/).filter(Boolean);
  const header = parseCsvLine(lines[0]);
  return lines.slice(1).map((line) => {
    const values = parseCsvLine(line);
    return Object.fromEntries(header.map((key, index) => [key, values[index] ?? ""]));
  });
}

async function launchBrowser(profileDir, headed) {
  const channels = ["msedge", "chrome"];
  let lastError;

  for (const channel of channels) {
    try {
      return await chromium.launchPersistentContext(profileDir, {
        channel,
        headless: !headed,
        acceptDownloads: true,
        viewport: { width: 1280, height: 900 },
      });
    } catch (error) {
      lastError = error;
    }
  }

  throw new Error(
    `Could not launch Edge or Chrome through Playwright. Install Microsoft Edge/Chrome, or install Playwright browsers. Last error: ${lastError}`,
  );
}

async function waitForManualLogin(page) {
  const currentUrl = page.url();
  const looksLoggedOut =
    currentUrl.includes("accounts.spotify.com") ||
    (await page.locator("text=/log in|sign in|agree|accept/i").count().catch(() => 0)) > 0;

  if (!looksLoggedOut) return;

  console.log("\nSpotify Charts appears to need login/consent.");
  console.log("Finish login in the opened browser window, then press Enter here to continue.\n");
  const rl = readline.createInterface({ input, output });
  await rl.question("Press Enter after login is complete...");
  rl.close();
}

async function pauseForLogin(page) {
  console.log("\nOpening Spotify Charts for login/check.");
  await page.goto("https://charts.spotify.com/home", { waitUntil: "domcontentloaded", timeout: 45000 });
  console.log("Log in or confirm the page is already logged in, then return here.");
  const rl = readline.createInterface({ input, output });
  await rl.question("Press Enter to start downloading...");
  rl.close();
}

async function moveNewestCsv(outDir, saveAs) {
  const files = await readdir(outDir);
  const csvFiles = [];
  for (const file of files) {
    if (!file.toLowerCase().endsWith(".csv")) continue;
    const fullPath = path.join(outDir, file);
    const info = await stat(fullPath);
    csvFiles.push({ file, fullPath, mtime: info.mtimeMs });
  }
  csvFiles.sort((a, b) => b.mtime - a.mtime);
  const newest = csvFiles[0];
  if (!newest) throw new Error("Download finished, but no CSV file was found in output directory.");
  const target = path.join(outDir, saveAs);
  if (newest.fullPath !== target) await rename(newest.fullPath, target);
}

async function clickDownload(page, outDir, saveAs) {
  const candidates = [
    page.getByRole("button", { name: "Download CSV" }),
    page.getByRole("button", { name: "Download" }),
    page.getByRole("button", { name: "CSV" }),
    page.getByRole("link", { name: "Download CSV" }),
    page.getByRole("link", { name: "Download" }),
    page.getByRole("link", { name: "CSV" }),
    page.locator('[aria-label*="Download" i]'),
    page.locator('[aria-label*="CSV" i]'),
    page.locator('[aria-label*="Export" i]'),
    page.locator('[title*="Download" i]'),
    page.locator('[title*="CSV" i]'),
    page.locator('button:has-text("Download")'),
    page.locator('a:has-text("Download")'),
    page.locator('button:has-text("CSV")'),
    page.locator('a:has-text("CSV")'),
    page.locator('button:has(svg)'),
  ];

  for (const locator of candidates) {
    const count = await locator.count().catch(() => 0);
    if (count === 0) continue;

    const first = locator.first();
    const downloadPromise = page.waitForEvent("download", { timeout: 15000 }).catch(() => null);
    await first.click({ timeout: 10000 });
    const download = await downloadPromise;
    if (download) {
      await download.saveAs(path.join(outDir, saveAs));
      return true;
    }

    await page.waitForTimeout(1500);
    await moveNewestCsv(outDir, saveAs).catch(() => {});
    if (existsSync(path.join(outDir, saveAs))) return true;
  }

  return false;
}

function setupNetworkSniffer(page) {
  const seen = new Set();
  const hits = [];

  page.on("request", (request) => {
    const url = request.url();
    if (!/(csv|download|export|chart|regional)/i.test(url)) return;
    const key = `req:${request.method()}:${url}`;
    if (seen.has(key)) return;
    seen.add(key);
    hits.push({ type: "request", method: request.method(), url, headers: request.headers() });
  });

  page.on("response", async (response) => {
    const url = response.url();
    const headers = response.headers();
    const contentType = headers["content-type"] || "";
    const disposition = headers["content-disposition"] || "";
    if (!/(csv|download|export|chart|regional)/i.test(url + contentType + disposition)) return;
    const key = `res:${response.status()}:${url}`;
    if (seen.has(key)) return;
    seen.add(key);
    hits.push({
      type: "response",
      status: response.status(),
      url,
      contentType,
      contentDisposition: disposition,
      headers,
    });
  });

  return () => hits;
}

function printSniffHits(hits) {
  console.log("\n[sniff] likely CSV/download/chart requests:");
  if (hits.length === 0) {
    console.log("[sniff] no matching network requests captured");
    return;
  }

  for (const hit of hits) {
    console.log(JSON.stringify(hit, null, 2));
  }
}

async function saveDebug(page, row) {
  mkdirSync(DEBUG_DIR, { recursive: true });
  const safeName = row.save_as.replace(/[^a-z0-9_.-]+/gi, "_");
  const htmlPath = path.join(DEBUG_DIR, `${safeName}.html`);
  const screenshotPath = path.join(DEBUG_DIR, `${safeName}.png`);
  await writeFile(htmlPath, await page.content(), "utf-8");
  await page.screenshot({ path: screenshotPath, fullPage: true }).catch(() => {});
  console.log(`[debug] Saved ${htmlPath}`);
  console.log(`[debug] Saved ${screenshotPath}`);

  const candidates = await page
    .locator('button, a, [role="button"], [aria-label], [title]')
    .evaluateAll((nodes) =>
      nodes.slice(0, 200).map((node) => ({
        tag: node.tagName,
        text: (node.textContent || "").trim().slice(0, 80),
        aria: node.getAttribute("aria-label") || "",
        title: node.getAttribute("title") || "",
        href: node.getAttribute("href") || "",
        role: node.getAttribute("role") || "",
      })),
    )
    .catch(() => []);
  console.log("[debug] Clickable candidates containing download/csv/export:");
  for (const item of candidates) {
    const text = `${item.text} ${item.aria} ${item.title} ${item.href}`.toLowerCase();
    if (/(download|csv|export)/.test(text)) console.log(JSON.stringify(item));
  }
}

async function main() {
  const options = parseArgs();
  mkdirSync(options.outDir, { recursive: true });
  mkdirSync(options.profileDir, { recursive: true });

  const rows = (await readManifest(options.links)).slice(options.startAt, options.startAt + options.limit);
  if (rows.length === 0) {
    console.log("No rows to process.");
    return;
  }

  const context = await launchBrowser(options.profileDir, options.headed);
  let page = await getUsablePage(context);
  let downloaded = 0;
  let skipped = 0;
  let failed = 0;

  try {
    if (options.loginFirst) {
      await pauseForLogin(page);
    }

    let apiHeaders = null;
    if (options.apiFast) {
      const firstPendingRow =
        rows.find((row) => !options.skipExisting || !existsSync(path.join(options.outDir, row.save_as))) ?? rows[0];
      apiHeaders = await captureApiHeaders(page, firstPendingRow);
      console.log("[auth] captured Spotify Charts API headers; switching to fast API downloads");
    }

    for (const [index, row] of rows.entries()) {
      const getSniffHits = options.sniff && index === 0 ? setupNetworkSniffer(page) : null;
      const savePath = path.join(options.outDir, row.save_as);
      if (options.skipExisting && existsSync(savePath)) {
        skipped += 1;
        console.log(`[skip] ${row.save_as}`);
        continue;
      }

      if (options.apiFast) {
        try {
          const count = await downloadViaApi(
            context,
            row,
            apiHeaders,
            options.outDir,
            options.retries,
            options.rateLimitSleepMs,
          );
          downloaded += 1;
          console.log(`[done] ${row.save_as} (${count} rows)`);
        } catch (error) {
          failed += 1;
          console.log(`[fail] ${error.message}`);
        }
        if (options.sleepMs > 0) await sleep(options.sleepMs);
        continue;
      }

      console.log(`[open ${options.startAt + index + 1}] ${row.url}`);
      await page.goto(row.url, { waitUntil: "domcontentloaded", timeout: 45000 });
      await waitForManualLogin(page);
      await page.waitForLoadState("networkidle", { timeout: 20000 }).catch(() => {});

      const ok = await clickDownload(page, options.outDir, row.save_as);
      if (ok) {
        downloaded += 1;
        console.log(`[done] ${row.save_as}`);
      } else {
        failed += 1;
        console.log(`[fail] Could not find/click Download CSV for ${row.url}`);
        await saveDebug(page, row);
      }

      if (getSniffHits) {
        await page.waitForTimeout(2000);
        printSniffHits(getSniffHits());
        break;
      }
    }
  } finally {
    await context.close();
  }

  console.log(`\nFinished. Downloaded: ${downloaded}, skipped: ${skipped}, failed: ${failed}`);
}

main().catch((error) => {
  console.error(`Spotify official download failed: ${error.message}`);
  process.exit(1);
});
